// <auto-generated />
using System;
using CarFinderAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarFinderAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarFinderAPI.Models.Car", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BodyType")
                        .HasMaxLength(32);

                    b.Property<double?>("Capacity");

                    b.Property<string>("Company")
                        .HasMaxLength(32);

                    b.Property<string>("DriveType")
                        .HasMaxLength(32);

                    b.Property<string>("Fuel")
                        .HasMaxLength(32);

                    b.Property<double?>("FuelConsumption");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Model")
                        .HasMaxLength(32);

                    b.Property<int?>("Power");

                    b.Property<int?>("Price");

                    b.Property<string>("Transmission")
                        .HasMaxLength(32);

                    b.Property<string>("Version")
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
